# run: conda env create -f environment.yml
name: inerf
channels:
  - pytorch
  - defaults
dependencies:
  - python>=3.8
  - pip
  - pip:
      - pyhocon==0.3.55
      - opencv-contrib-python==4.5.5.64
      # - dotmap
      - tensorboard
      - imageio
      - imageio-ffmpeg
      # - ipdb
      # - pretrainedmodels
      # - lpips
  - scipy
  - numpy
  - matplotlib
  - configargparse
  # - pytorch==1.8.1
  # - torchvision==0.9.1
  - scikit-image
  - tqdm
